name: safety_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase y Notificaciones (Versiones actualizadas y compatibles)
  awesome_notifications:
    git:
      url: https://github.com/rafaelsetragni/awesome_notifications.git
      ref: master
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_storage: ^13.0.0
  cloud_functions: ^6.0.0
  shared_preferences: ^2.2.3
  firebase_app_check: 0.4.0


  # Selección y subida de archivos
  file_picker: ^10.3.2

  # Gestión de estado y compras
  provider: ^6.1.2
  purchases_flutter: ^9.3.0

  # Almacenamiento Local y Utilidades
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  intl: ^0.20.0
  logging: ^1.2.0
  flutter_dotenv: ^6.0.0

  change_app_package_name: ^1.5.0

  # UI y otros
  cupertino_icons: ^1.0.8
  google_maps_flutter:
  geolocator: ^14.0.2
  font_awesome_flutter: ^10.7.0
  google_mobile_ads: ^6.0.0
  http: ^1.2.1
  url_launcher: ^6.3.2
  dio: ^5.8.0+1
  permission_handler: ^12.0.1
  flutter_pdfview: ^1.4.1+1
  device_info_plus: ^11.5.0
  open_filex: ^4.7.0
  flutter_native_splash: ^2.4.6
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  hive_generator: ^2.0.1

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

# --- ✅ CONFIGURACIÓN AÑADIDA AQUÍ ---
flutter_native_splash:
  color: "#FFFFFF"       # El color de fondo de tu splash
  image: assets/images/logo.png # La ruta a tu logo
  android: true
  ios: true