name: safety_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Paquetes de Firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_messaging: ^15.0.3

  # Paquetes de UI y utilidades
  font_awesome_flutter: ^10.7.0
  geolocator: ^14.0.1
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.2.1
  logger: ^2.4.0

  intl: ^0.19.0 # Para formatear fechas

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1 # <-- La dependencia aquí

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# LA CONFIGURACIÓN VA AQUÍ, AL FINAL Y SIN INDENTACIÓN
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/logo.png