// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmRsR1dY1s4_SHWYovgpR-hxdUodzjMHw',
    appId: '1:868936144588:android:0b3c9c031926ccce169469',
    messagingSenderId: '868936144588',
    projectId: 'safetymex-7d9c6',
    databaseURL: 'https://safetymex-7d9c6-default-rtdb.firebaseio.com',
    storageBucket: 'safetymex-7d9c6.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMvG587RZETw0p17PbEz-zlhNm00NvaX8',
    appId: '1:868936144588:web:0f907a131de2dd38169469',
    messagingSenderId: '868936144588',
    projectId: 'safetymex-7d9c6',
    authDomain: 'safetymex-7d9c6.firebaseapp.com',
    databaseURL: 'https://safetymex-7d9c6-default-rtdb.firebaseio.com',
    storageBucket: 'safetymex-7d9c6.firebasestorage.app',
    measurementId: 'G-D7PH7GGZ1Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp4tvrniaz-W2IZvhi-2Sy9cp5AwfS8eg',
    appId: '1:868936144588:ios:090b37fea5025460169469',
    messagingSenderId: '868936144588',
    projectId: 'safetymex-7d9c6',
    databaseURL: 'https://safetymex-7d9c6-default-rtdb.firebaseio.com',
    storageBucket: 'safetymex-7d9c6.firebasestorage.app',
    androidClientId: '868936144588-3kp3u44n8v60h8gi4kq3k2q6tab9j2d9.apps.googleusercontent.com',
    iosClientId: '868936144588-49n5ni0t55lfqfm6isdf9410pc49umtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.safetyAppNew',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp4tvrniaz-W2IZvhi-2Sy9cp5AwfS8eg',
    appId: '1:868936144588:ios:2e4fa3e4eed6ff51169469',
    messagingSenderId: '868936144588',
    projectId: 'safetymex-7d9c6',
    databaseURL: 'https://safetymex-7d9c6-default-rtdb.firebaseio.com',
    storageBucket: 'safetymex-7d9c6.firebasestorage.app',
    androidClientId: '868936144588-3kp3u44n8v60h8gi4kq3k2q6tab9j2d9.apps.googleusercontent.com',
    iosClientId: '868936144588-hk2i6lt79cs9scii5dc4hv2msgle5i3i.apps.googleusercontent.com',
    iosBundleId: 'com.safetyapp.mobile',
  );

}